# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020-2022 Intel Corporation
#
# vim: syntax=dockerfile

# Build command from bess root directory to build besscndp docker image
# docker build --build-arg http_proxy=$http_proxy \
# --build-arg https_proxy=$http_proxy --build-arg no_proxy="$no_proxy" \
# -t besscndp -f env/Dockerfile-cndp .

ARG BASE_IMAGE=ubuntu:focal
# Install CNDP dependencies and build CNDP.
FROM ${BASE_IMAGE} AS cndpbuild

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    build-essential \
    golang \
    libelf-dev \
    meson \
    pkg-config \
    libbsd-dev \
    libbpf-dev \
    libjson-c-dev \
    libnl-3-dev \
    libnl-cli-3-dev \
    libnuma-dev \
    libpcap-dev \
    git

# Get CNDP from GitHub
RUN git clone https://github.com/CloudNativeDataPlane/cndp.git
WORKDIR /cndp
# Use version of CNDP tested with BESS
RUN git checkout 740d37d0eafa5de85900662f3d653f3777171a5d
# Build and install CNDP shared libraries
RUN make && make install
# Build and install CNDP static libraries
RUN make static_build=1 rebuild install

# Build the prometheus-metrics app
WORKDIR /cndp/lang/go/stats/prometheus/
RUN go build prometheus.go

# Build Bess
FROM ${BASE_IMAGE} AS bessimage

# Copy CNDP dependencies
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    build-essential \
    ethtool \
    libbsd-dev \
    libbpf-dev \
    libelf1 \
    libjson-c-dev \
    libnl-3-dev \
    libnl-cli-3-dev \
    libnuma1 \
    libpcap0.8 \
    pkg-config

# Copy required CNDP libraries, header files, pkg-config and binaries.
COPY --from=cndpbuild /cndp/usr/local/bin/cndpfwd /usr/bin/
COPY --from=cndpbuild /cndp/usr/local/lib/x86_64-linux-gnu/*.so /usr/local/lib/x86_64-linux-gnu/
COPY --from=cndpbuild /cndp/usr/local/lib/x86_64-linux-gnu/*.a /usr/local/lib/x86_64-linux-gnu/
COPY --from=cndpbuild /cndp/usr/local/include/cndp /usr/local/include/cndp
COPY --from=cndpbuild /cndp/usr/local/lib/pkgconfig/libcndp.pc /usr/local/lib/x86_64-linux-gnu/pkgconfig/
COPY --from=cndpbuild /cndp/lang/go/stats/prometheus/prometheus /usr/bin/

# Set CNDP PKG_CONFIG_PATH
ENV PKG_CONFIG_PATH=/usr/local/lib/x86_64-linux-gnu/pkgconfig

# Install BESS
RUN echo "APT::Install-Recommends false;" >> /etc/apt/apt.conf.d/00recommends && \
	echo "APT::Install-Suggests false;" >> /etc/apt/apt.conf.d/00recommends && \
	echo "APT::AutoRemove::RecommendsImportant false;" >> /etc/apt/apt.conf.d/00recommends && \
	echo "APT::AutoRemove::SuggestsImportant false;" >> /etc/apt/apt.conf.d/00recommends

COPY env/build-dep.yml /tmp/
COPY env/kmod.yml /tmp/
COPY env/ci.yml /tmp/

# Install dependency packages with Ansible
RUN apt-get -q update && \
	apt-get install -y ansible curl git sudo libgraph-easy-perl python-is-python3 && \
        ansible-playbook /tmp/ci.yml -i "localhost," -c local && \
	apt-get purge -y ansible && \
	apt-get autoremove -y && \
	rm -rf /var/lib/apt/lists
RUN python3 -m pip install --upgrade pip && python3 -m pip install grpcio scapy protobuf==3.20.0 flask

RUN mkdir -p /build/bess
RUN mkdir -p /build/bess/log

# Copy required files and build bess
WORKDIR /build/bess
COPY bessctl bessctl
COPY bin bin
COPY core core
COPY deps/*.patch deps/
COPY env env
COPY protobuf protobuf
COPY pybess pybess
COPY sample_plugin sample_plugin
COPY build.py container_build.py install_git_hooks.sh ./
RUN ./build.py bess
RUN cp /build/bess/deps/dpdk-20.11.3/build/app/dpdk-testpmd /usr/local/bin/

ENV CCACHE_DIR=/tmp/ccache
ENV CCACHE_COMPRESS=true

WORKDIR /build/bess
